import assert from "node:assert/strict";
import { after, before, describe, it } from "node:test";

import { cleanUp, fixture, generate, HAS_FAUST } from "./helpers.mjs";

describe("code generation", { skip: HAS_FAUST ? false : "faust not on PATH" }, () => {
  let widgets;
  let kit;

  before(() => {
    widgets = generate([fixture("test_widgets")]);
    kit = generate([fixture("test_synth"), fixture("test_widgets")], [
      "-n",
      "test-kit",
    ]);
  });

  after(cleanUp);

  describe("TypeScript wrapper", () => {
    it("exposes each FAUST control as an AudioParam", () => {
      const ts = widgets.read("src/TestWidgetsNode.ts");
      for (const prop of ["gain", "depth", "mode", "bypass", "go"]) {
        assert.match(ts, new RegExp(`public readonly ${prop}: AudioParam;`));
      }
    });

    // The raw JSI host object has no `context`, which AudioNode.connect
    // compares against, so an unwrapped param cannot be a connect() target.
    it("wraps params in the AudioParam class, with the node's context", () => {
      assert.match(
        widgets.read("src/TestWidgetsNode.ts"),
        /this\.gain = new AudioParam\(node\.getAudioParam\("\/test_widgets\/gain"\), context\);/
      );
      assert.match(
        widgets.read("src/TestWidgetsNode.ts"),
        /^import \{\n  AudioNode,\n  AudioParam,\n  BaseAudioContext,\n\} from "react-native-audio-api";$/m
      );
    });

    // Bargraphs are DSP outputs, so FaustParamCapture records no AudioParam
    // for them. Emitting an accessor anyway would resolve to nothing at runtime.
    it("omits bargraphs", () => {
      const ts = widgets.read("src/TestWidgetsNode.ts");
      assert.doesNotMatch(ts, /level/);
      assert.match(widgets.stdout, /Skipped .*: level/);
    });

    // FAUST reports no init/min/max for buttons and check buttons, which used
    // to reach the docs verbatim as "min: undefined".
    it("documents a range for every control, gates included", () => {
      const ts = widgets.read("src/TestWidgetsNode.ts");
      assert.doesNotMatch(ts, /undefined/);
      assert.match(ts, /\/\*\* button — min: 0, max: 1, default: 0 \*\//);
      assert.match(ts, /\/\*\* checkbox — min: 0, max: 1, default: 0 \*\//);
    });

    // These four scalar methods duplicated the AudioParam API with divergent
    // semantics — silent no-ops on a miss and a different parameter ordering.
    it("does not carry the removed scalar parameter API", () => {
      const ts = widgets.read("src/TestWidgetsNode.ts");
      for (const method of [
        "setParam",
        "getParam(",
        "getParamCount",
        "getParamAddress",
      ]) {
        assert.ok(!ts.includes(method), `expected no ${method} in wrapper`);
      }
    });

    it("names properties from the FAUST shortname, dropping stray characters", () => {
      // The control is `button("go!")`, addressed as "/test_widgets/go!".
      const ts = widgets.read("src/TestWidgetsNode.ts");
      assert.match(ts, /public readonly go: AudioParam;/);
      assert.match(ts, /getAudioParam\("\/test_widgets\/go!"\)/);
    });
  });

  describe("C++ node", () => {
    // processKRateParam bounds neither scheduled automation nor modulation
    // from a connected node, but FAUST compiles the DSP assuming its controls
    // stay inside the declared range.
    it("clamps the k-rate value before writing it into the FAUST zone", () => {
      assert.match(
        widgets.read("shared/TestWidgetsNode.cpp"),
        /\*param\.zone =\s*static_cast<FAUSTFLOAT>\(std::clamp\(value, param\.min, param\.max\)\);/
      );
    });

    it("rejects a getAudioParam call with no arguments", () => {
      assert.match(
        widgets.read("shared/TestWidgetsNodeHostObject.cpp"),
        /if \(count < 1 \|\| !args\[0\]\.isString\(\)\)/
      );
    });

    it("registers a JSI factory per node", () => {
      const installer = kit.read("shared/ProcessorInstaller.cpp");
      assert.match(installer, /"createTestSynthNode"/);
      assert.match(installer, /"createTestWidgetsNode"/);
    });
  });

  describe("package layout", () => {
    it("derives package and node names from the DSP filename", () => {
      assert.match(widgets.stdout, /Package: test-widgets-nodes/);
      assert.match(widgets.stdout, /TestWidgetsNode:/);
    });

    it("derives package names from -n and node names per DSP", () => {
      assert.match(kit.stdout, /Package: test-kit-nodes/);
      const index = kit.read("src/index.ts");
      assert.match(index, /export \{ TestSynthNode \} from ".\/TestSynthNode";/);
      assert.match(
        index,
        /export \{ TestWidgetsNode \} from ".\/TestWidgetsNode";/
      );
    });

    it("marks generated files as generated", () => {
      assert.match(kit.read("src/index.ts"), /generated by faust2rnaa/);
      assert.match(kit.read("shared/TestSynthNode.h"), /generated by faust2rnaa/);
    });
  });
});
